// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoolTracker.Api.Data;

#nullable disable

namespace PoolTracker.Api.Migrations
{
    [DbContext(typeof(PoolTrackerDbContext))]
    [Migration("20260618113849_AddPlayerExperience")]
    partial class AddPlayerExperience
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.CueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccuracyBonus")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("AchievementCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CueControlBonus")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("PowerBonus")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopCost")
                        .HasColumnType("integer");

                    b.Property<decimal>("SpinBonus")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CueItems");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.Duel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpponentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointsWager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OpponentId");

                    b.HasIndex("WinnerUserId");

                    b.ToTable("Duels");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.DuelCoinFlip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DuelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FirstChooserSide")
                        .HasColumnType("integer");

                    b.Property<Guid>("FirstChooserUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResultSide")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondChooserSide")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SecondChooserUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DuelId")
                        .IsUnique();

                    b.HasIndex("FirstChooserUserId");

                    b.HasIndex("SecondChooserUserId");

                    b.HasIndex("WinnerUserId");

                    b.ToTable("DuelCoinFlips");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.DuelResultSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Choice")
                        .HasColumnType("integer");

                    b.Property<Guid>("DuelId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("DuelId", "SubmittedByUserId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("DuelResultSubmissions");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.HallDayCompetition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PoolDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PoolHallId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<int>("WinnerBallsPotted")
                        .HasColumnType("integer");

                    b.Property<int>("WinnerGamesWon")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoolDate");

                    b.HasIndex("WinnerUserId");

                    b.HasIndex("PoolHallId", "PoolDate")
                        .IsUnique();

                    b.ToTable("HallDayCompetitions");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.HallDayCompetitionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BallsPotted")
                        .HasColumnType("integer");

                    b.Property<int>("GamesLost")
                        .HasColumnType("integer");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer");

                    b.Property<Guid>("HallDayCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("HallDayCompetitionId", "UserId")
                        .IsUnique();

                    b.ToTable("HallDayCompetitionEntries");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PlayerDailyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBallsPotted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGamesLost")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGamesWon")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("PlayerDailyMetrics");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("AvatarColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<decimal>("CueControl")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("DebtPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DuelsLost")
                        .HasColumnType("integer");

                    b.Property<int>("DuelsWon")
                        .HasColumnType("integer");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<int?>("FavoriteBallNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<decimal>("Power")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Spin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Title")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PointsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("PointsDelta")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PointsTransactions");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("TotalTables")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.ToTable("PoolHalls");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHallRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BallsQuality")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CueQuality")
                        .HasColumnType("integer");

                    b.Property<int>("Lighting")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<Guid>("PoolHallId")
                        .HasColumnType("uuid");

                    b.Property<int>("PriceValue")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RatingDate")
                        .HasColumnType("date");

                    b.Property<int>("TableQuality")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PoolHallId", "UserId", "RatingDate")
                        .IsUnique();

                    b.ToTable("PoolHallRatings");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHallTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PoolHallId")
                        .HasColumnType("uuid");

                    b.Property<string>("TableLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("PoolHallId", "TableLabel")
                        .IsUnique();

                    b.ToTable("PoolHallTables");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHallTableRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClothQuality")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CushionQuality")
                        .HasColumnType("integer");

                    b.Property<int>("Levelness")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<Guid>("PoolHallTableId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RatingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PoolHallTableId", "UserId", "RatingDate")
                        .IsUnique();

                    b.ToTable("PoolHallTableRatings");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EndReason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PoolHallId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PoolHallTableId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoolHallId");

                    b.HasIndex("PoolHallTableId");

                    b.HasIndex("UserId", "IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.SessionGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BallsPotted")
                        .HasColumnType("integer");

                    b.Property<int>("BattleType")
                        .HasColumnType("integer");

                    b.Property<int>("BreakPots")
                        .HasColumnType("integer");

                    b.Property<bool>("BrokeThisRack")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameType")
                        .HasColumnType("integer");

                    b.Property<bool>("GoldenBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("PottedTrain")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SnookersEscaped")
                        .HasColumnType("integer");

                    b.Property<int>("SnookersFaced")
                        .HasColumnType("integer");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("SessionGames");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.SessionReport", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccuracyDelta")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("BallsPotted")
                        .HasColumnType("integer");

                    b.Property<int>("BallsPottedOnBreak")
                        .HasColumnType("integer");

                    b.Property<decimal>("CueControlDelta")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("FlaggedForValidation")
                        .HasColumnType("boolean");

                    b.Property<int>("GamesBroken")
                        .HasColumnType("integer");

                    b.Property<int>("GamesLost")
                        .HasColumnType("integer");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer");

                    b.Property<int>("GoldenBreaks")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<decimal>("PowerDelta")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("SnookersEscaped")
                        .HasColumnType("integer");

                    b.Property<int>("SnookersFaced")
                        .HasColumnType("integer");

                    b.Property<decimal>("SpinDelta")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.ToTable("SessionReports");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.UserCueInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CueItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CueItemId");

                    b.HasIndex("UserId", "CueItemId")
                        .IsUnique();

                    b.ToTable("UserCueInventories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.Duel", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "Challenger")
                        .WithMany()
                        .HasForeignKey("ChallengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "WinnerUser")
                        .WithMany()
                        .HasForeignKey("WinnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Challenger");

                    b.Navigation("Opponent");

                    b.Navigation("WinnerUser");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.DuelCoinFlip", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.Duel", "Duel")
                        .WithOne("CoinFlip")
                        .HasForeignKey("PoolTracker.Api.Domain.Entities.DuelCoinFlip", "DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "FirstChooserUser")
                        .WithMany()
                        .HasForeignKey("FirstChooserUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "SecondChooserUser")
                        .WithMany()
                        .HasForeignKey("SecondChooserUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "WinnerUser")
                        .WithMany()
                        .HasForeignKey("WinnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Duel");

                    b.Navigation("FirstChooserUser");

                    b.Navigation("SecondChooserUser");

                    b.Navigation("WinnerUser");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.DuelResultSubmission", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.Duel", "Duel")
                        .WithMany("ResultSubmissions")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Duel");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.HallDayCompetition", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.PoolHall", "PoolHall")
                        .WithMany()
                        .HasForeignKey("PoolHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "WinnerUser")
                        .WithMany()
                        .HasForeignKey("WinnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PoolHall");

                    b.Navigation("WinnerUser");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.HallDayCompetitionEntry", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.HallDayCompetition", "Competition")
                        .WithMany("Entries")
                        .HasForeignKey("HallDayCompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PlayerDailyMetric", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("PoolTracker.Api.Domain.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PointsTransaction", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHall", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUser");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHallRating", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.PoolHall", "PoolHall")
                        .WithMany("Ratings")
                        .HasForeignKey("PoolHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoolHall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHallTable", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.PoolHall", "PoolHall")
                        .WithMany("Tables")
                        .HasForeignKey("PoolHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("PoolHall");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHallTableRating", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.PoolHallTable", "PoolHallTable")
                        .WithMany("Ratings")
                        .HasForeignKey("PoolHallTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoolHallTable");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.Session", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.PoolHall", "PoolHall")
                        .WithMany()
                        .HasForeignKey("PoolHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.PoolHallTable", "PoolHallTable")
                        .WithMany()
                        .HasForeignKey("PoolHallTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoolHall");

                    b.Navigation("PoolHallTable");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.SessionGame", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.Session", "Session")
                        .WithMany("Games")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.SessionReport", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.Session", "Session")
                        .WithOne("Report")
                        .HasForeignKey("PoolTracker.Api.Domain.Entities.SessionReport", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.UserCueInventory", b =>
                {
                    b.HasOne("PoolTracker.Api.Domain.Entities.CueItem", "CueItem")
                        .WithMany()
                        .HasForeignKey("CueItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTracker.Api.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CueItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.Duel", b =>
                {
                    b.Navigation("CoinFlip");

                    b.Navigation("ResultSubmissions");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.HallDayCompetition", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHall", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.PoolHallTable", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("PoolTracker.Api.Domain.Entities.Session", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Report");
                });
#pragma warning restore 612, 618
        }
    }
}
