namespace PoolTracker.Api.Features.Profile.Contracts;

public sealed record ProfileResponse(
    Guid UserId,
    string DisplayName,
    string Email,
    string AvatarColorHex,
    int? FavoriteBallNumber,
    int Points,
    int DebtPoints,
    string? Title,
    decimal Power,
    decimal Accuracy,
    decimal CueControl,
    decimal Spin,
    decimal EffectivePower,
    decimal EffectiveAccuracy,
    decimal EffectiveCueControl,
    decimal EffectiveSpin,
    int DuelsWon,
    int DuelsLost,
    int GamesWon,
    int GamesLost,
    int Level,
    string LevelTitle,
    long Experience,
    int ExperienceIntoLevel,
    int ExperienceForNextLevel,
    DateTimeOffset UpdatedAtUtc
);
